const products =[
    {   
        category : `apparel`,
                // + shoes 
                // + accessories
        name : `BADGE OF SPORT FRENCH TERRY PANTS`,
        brand : `adidas`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey'],
        gender : ['male'],
                // female
        price : 50,
        productType : `pants`,
            // t-shirt, pants , suits ,trousers ,...
    },
    {   
        category : `apparel`,
        name : `CONTINENT CAMO CITY LONG SHORTS`,
        brand : `adidas`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey','gold'],
        gender : ['male'],
        price : 45,
        productType : `shorts`,
    },
    {   
        category : `apparel`,
        name : `COLD.RDY DOWN JACKET`,
        brand : `adidas`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey'],
        gender : ['male'],
        price : 400,
        productType : `jacket`,
    },
    {   
        category : `shoes`,
        name : `ZX 2K BOOST SHOES`,
        brand : `adidas`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['black','pink','blue','white'],
        gender : ['male','female'],
        price : 150,
        productType : `originals`,
    },
    {   
        category : `shoes`,
        name : `DONOVAN MITCHELL D.O.N. ISSUE #2 CRAYOLA SHOES`,
        brand : `adidas`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['cyan','yellow','black','white'],
        gender : ['male','female'],
        price : 700,
        productType : `originals`,
    },
    {   
        category : `shoes`,
        name : `X9000L4 SHOES`,
        brand : `adidas`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['cyan','yellow','black','white'],
        gender : ['female'],
        price : 500,
        productType : `running`,
    },
    {   
        category : `apparel`,
        name : `TREFOIL HOODIE`,
        brand : `adidas`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black'],
        gender : ['female'],
        price : 65,
        productType : `hoodie`,
    },
    {   
        category : `apparel`,
        name : `ADIDAS X ZOE SALDANA COLLECTION WOMEN'S LONG SLEEVE SHIRT`,
        brand : `adidas`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','blue'],
        gender : ['male'],
        price : 40,
        productType : `shirt`,
    },
    {   
        category : `apparel`,
        name : `ADIDAS X ZOE SALDANA COLLECTION WOMEN'S TIGHT`,
        brand : `adidas`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey'],
        gender : ['female'],
        price : 55,
        productType : `tight`,
    },
    {   
        category : `apparel`,
        name : `COLD.RDY DOWN JACKET`,
        brand : `adidas`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey'],
        gender : ['female'],
        price : 400,
        productType : `jacket`,
    }, 
]